# Generated by Django 6.0 on 2025-12-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('PLANETA', 'Planeta'), ('GALAXIA', 'Galáxia'), ('COMETA', 'Cometa'), ('ASTEROIDE', 'Asteroide'), ('CINTURA_DE_ASTEROIDES', 'Cintura de Asteroides'), ('OUTROS', 'Outros')], default='OUTROS', max_length=100),
        ),
    ]
